#define a using
#define aa namespace
#define aaa std;
#define aaaa int
#define aaaaa main
#define aaaaaa srand
#define aaaaaaa unsigned
#define aaaaaaaa time
#define aaaaaaaaa NULL
#define aaaaaaaaaa for
#define aaaaaaaaaaa i
#define aaaaaaaaaaaa 5
#define aaaaaaaaaaaaa i++
#define aaaaaaaaaaaaaa 1
#define aaaaaaaaaaaaaaa random
#define aaaaaaaaaaaaaaaa =
#define aaaaaaaaaaaaaaaaa 100
#define aaaaaaaaaaaaaaaaaaa rand()
#define aaaaaaaaaaaaaaaaaaaaa 101
#define aaaaaaaaaaaaaaaaaaaaaa cout
#define aaaaaaaaaaaaaaaaaaaaaaa endl;